book:
  site-url: "https://acep-uaf.github.io/aetr-web-book-2024/" 
  repo-url: https://github.com/acep-uaf/aetr-web-book-2024 
  other-links: 
    - href: mailto:uaf-acep-dcm-support@alaska.edu
      text: Report an issue via email
      icon: envelope-exclamation
    - href: https://acep-uaf.github.io/ak-energy-statistics-2011_2021/
      text: Alaska Energy Statistics Workbooks (2011-2021)
      icon: bi-file-spreadsheet
  repo-actions: [issue]

  chapters:
    - index.qmd
    - methods.qmd
    - capacity.qmd
    - generation.qmd
    - consumption.qmd
    - prices.qmd
    - conclusions.qmd
    - data.qmd
  appendices:
    - about.qmd
    - historic_reports.qmd
    - acronyms.qmd
    - credits.qmd 

  sidebar:
    logo: "images/ACEP_gear.png"
    pinned: true
    align: center
    title: "<strong>2024 Alaska Electricity Trends Report</strong><br/><small><em>(Data Years 2011-2021)</em></small><br/>"
    tools: 
      - icon: globe
        href: https://www.uaf.edu/acep/
        text: "Alaska Center for Energy and Power"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: "&copy; [CC BY-SA 4.0](https://github.com/acep-uaf/aetr-web-book-2024/blob/main/LICENSE.md), 2024<br /> [Alaska Center for Energy and Power](https://www.uaf.edu/acep/)"

# These change page titles https://quarto.org/docs/books/book-structure.html#parts-appendices 
# but not in the sidebar navigation or in cross-references
crossref:
  appendix-title: "Appendix"
  appendix-delim: ":"

format:
  html:
    anchor-sections: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    # fig-align: center  Tried this but it overridden by Observable defaults (bootstrap?) 
    number-depth: 2
    theme:
      light: [cosmo, theme.scss, custom.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      #dark: [cosmo, theme-dark.scss]
    toc: true

date: last-modified
date-format: "MMM D, YYYY [at] HH:mm z"

filters:
  - quarto