project: 
  type: book
  
book:
  title: "2024 Alaska Electricity Trends Report"
  author: "Alaska Center for Energy and Power"
  description: An interactive report that summarizes federal, state, and utility electricity data for Alaska.
  keyword: Alaska, energy, capacity, generation, price, rates

profile:
  group: 
    - [pdf, html]